### ISSUE TITLE
Raneto Docs Website down

### ISSUE THREAD

**Issue by lonivenn** [ryanlelek/Raneto#182]
Sorry in advance if this is not the appropriate place to let you know the docs website is down. I just need access to the user manual so I can start creating my knowledge base now that I have Raneto installed! 

Checked from different networks, so it does appear to me that the problem is on Raneto's side.

**Comment by ryanlelek** [comment]
Thanks for reporting.
That may have been the case.

It's online now.  
Because it's hosted on Heroku it's possible they had issues or it was "spinning up" (about 20 seconds) since it's on the free plan.

This will be improved soon
Closing this and let us know if it happens again.

If you're using Raneto in a public setting, we'd love to know so we can put it in the showcase.
