### ISSUE TITLE
Issue: Raneto - Heroku, not saving anything!

### ISSUE THREAD

**Issue by Livonias** [ryanlelek/Raneto#267]
I followed the instructions from your documentation to host Raneto on Heroku.
http://docs.raneto.com/tutorials/deploying-raneto-to-heroku

Everything went well and it's hosted nicely with my custom domain, so far so good ;-)!

However...When I make new categories or pages and I restart the dyno, everything newly created is gone. It doesn't save the pages or newly made categories. It only shows the (default) pages which are placed in /example/content/.

Any help would be greatly appreciated!

Thanks,
Justin.

**Comment by Livonias** [comment]
I've purchased another VPS to host Raneto, so this can be closed for me. However I think others will still have the same problem as I had when they host on Heroku.

**Comment by dharmendra1986** [comment]
Even I am facing the same issue. couldn't find any workaround for that.

**Comment by hplageman** [comment]
You must push to your own repo first, after connecting it with Heroku
git add .
git push
git commit
git push heroku master

**Comment by hplageman** [comment]
I figured this out. Sign in and make your changes on your LOCAL repository, then push to the remote one. Do not make your changes on your herokuapp instance, as the changes will not be accessible.

**Comment by ryanlelek** [comment]
Hi, you're right. and thank you for submitting.

Heroku is "stateless" and will not persist data. This is because the "web" dynos (servers) get destroyed like you mention.
Further reading on Heroku's deployments at [12Factor](https://12factor.net/)

By editing locally and committing your changes to git, the Heroku dyno will have the files when it restarts from zero.

I'll mark this in the upcoming Documentation megathread (link is above this comment) so we can make sure this is clear in our docs. Hopefully updating the docs will prevent future frustration.
