### ISSUE TITLE
Unclear install instructions

### ISSUE THREAD

**Issue by ArtFlag** [ryanlelek/Raneto#324]
I went through the docs and I was a bit confused by the install instructions. 

I'm happy to send in a PR to update things, but I just need some info on the following line, in the [install page](https://github.com/gilbitron/Raneto/blob/master/example/content/install/installing-raneto.md)

```
Add Raneto to your project via NPM's package.json file
```
Do we mean `npm install raneto` ? That didn't help in my case, I had to downlod the whole repo to my repo.
What do we mean exactly? I'm not so familiar with Node and getting stuck at the install step is always a big issue for any project's adopotion rate.

**Comment by ryanlelek** [comment]
No worries, thank you for pointing out that we can have more detailed instructions.
I'll work on this tomorrow :)

**Comment by ArtFlag** [comment]
I've open a small PR for some updates. Feel free to use it to add your changes!

**Comment by Aaron128l** [comment]
I too was a bit confused when trying to import a base Raneto project. I started solely using the `/example` directory as the base of the project.
After `npm install` to get the `raneto` & `debug` dependencies. Two files had to be changed immediately.

[server.js](https://github.com/gilbitron/Raneto/blob/master/example/server.js)
- Comment out the `require('../app/index.js')` and uncomment the `require('raneto');` line

[config.default.js](https://github.com/gilbitron/Raneto/blob/master/example/config.default.js)
- Change `theme_dir` to not go up a [directory](https://github.com/gilbitron/Raneto/blob/master/example/config.default.js#L37) (removing `..`)
- Change public_dir to not go up a [directory](https://github.com/gilbitron/Raneto/blob/master/example/config.default.js#L46) (removing `..`)

After additional troubleshooting:

I realized that the default theme couldn't be accessed (unless I changed the config to target the `./node_modules/raneto/themes/default/public`), so I copied the `themes` folder to my base directory.

The config file wouldn't load the favicon from my base directory due to the `config.default.js` config file being changed [after initalized](https://github.com/gilbitron/Raneto/blob/master/example/config.default.js#L136). The line should be from the default config file altogether. 

The lib files weren't found on my localhost:3000 port. After digging deeper the `lib` directory is made from gulp which isn't run. 

At this point, I just reverted to cloning the entire Raneto project and editing the example project in place. The example directory in the folder needs to be a standalone entity in the project that runs without any relative links to the project or the [install page](https://github.com/gilbitron/Raneto/blob/master/example/content/install/installing-raneto.md) needs to be updated to reflect that you need the entire project. Sidenote `npm run start_win` doesn't exist in the example [package.json](https://github.com/gilbitron/Raneto/blob/master/example/package.json).

The `start_win` script can probably be removed altogether with something like [cross-env](https://www.npmjs.com/package/cross-env).

Overall Raneto is great but configuring everything for the initial setup I feel can be simplified. Thanks!

**Comment by johnchristopher** [comment]
Something's off. A few years ago I used Raneto on Heroku. Now I want to run a local instance with my markdown knowledge base folder as content but even renaming that folder to `content` doesn't work. I installed raneto through npm and with git+compile but localhost:3000 still displays the default documentation.

The documentation needs a working example, with markdown files from an arbitrary folder.

**Comment by ryanlelek** [comment]
Would keeping the Raneto module/package more "library-focused" help?

We could then have a separate examples for all the ways people deploy, instead of the one `example/` directory in the repo which seems to be causing some confusion

#330 also related

**Comment by ryanlelek** [comment]
Linking this to the Documentation megathread (see link above this comment)
Please join the discussion there or re-open the issue with further questions
