### ISSUE TITLE
What if I want to use as library instead run the entire source code?

### ISSUE THREAD

**Issue by jrichardsz** [ryanlelek/Raneto#330]
According to some researches, is mandatory the use of the internal folder **example** to use Raneto. 

That is fine but some folks might want to use as simple npm module. I tried:

```
var raneto = require('raneto');
var config = require('./config.default.js');
var app = raneto(config);
var server = app.listen(app.get('port'), function () {
  console.log('Express HTTP server listening on port ' + server.address().port);
});
```

So in order to make this works, I need to install as npm module:

    npm i raneto --save

This throws an error:

    gulp not found

That is because gulp is in **devDependencies**. 

I think gulp is not just a **dev** library for Raneto. 
Due to Raneto necesity of **public/lib** folder with several js files, I think must be moved to **dependencies**.
 
I moved it and this error dissapear

**Comment by ryanlelek** [comment]
Can you provide more of your use-case and what you're trying to accomplish?
Typically the `public/` directory would not need to be used for a Node "library" but it depends on how it is used.
Please give us an idea and we can better advise.

Are you looking to use the markdown rendering engines alone?
An embeddable widget on pages?

**Comment by jrichardsz** [comment]
Hi. 

I mean that if I want to use raneto, I need the entire source code of raneto. Is it correct?

Comparing with similar frameworks or thinking as a library maker, it would be grateful if Raneto will be able to be used as library, instead to clone the entire Raneto source code.

**Comment by ryanlelek** [comment]
`I need the entire source code of raneto. Is it correct?`
Yes and no.

While we provide a "quickstart" where you can clone this repo and immediately try out Raneto by running on your local machine, it's not required.

All you technically need is the "example/" directory.
Then change `example/server.js" line
`var raneto = require('../app/index.js');`
to be `var raneto = require('raneto');

and add `raneto` to your `package.json` file and run `npm install` as usual.

So it's currently sort of a library.
There may be additional bumps on that road as you mentioned because `gulp` and other generators would not be installed.

We'll add testing via library to the list of to-dos

**Comment by ryanlelek** [comment]
Adding this to the Roadmap megathread.
Closing this issue to cleanup
