### ISSUE TITLE
Separate Google Authentications for Viewing/Editing

### ISSUE THREAD

**Issue by DoctorRiceYouSee** [ryanlelek/Raneto#334]
The way I have it set up is that to access the website, you have to sign in with Google OAuth. I was wondering if there was a way where the user has to log in using Google OAuth to access the website and on the top right of the page, there's another login button for administrative use for editing/deleting/ etc?

So basically, I want the user to be able to log in using Google Oauth to access the website but not be able to edit.
And then I want there to be a separate login for Admins to edit pages, preferebly using Google OAuth as well.

Hope that makes sense. Thanks in advance!

Here's my config file for that stuff: 
![IMG_4825](https://user-images.githubusercontent.com/27183506/99299408-08f02900-2800-11eb-8a33-acb260200f4f.JPG)

**Comment by ryanlelek** [comment]
Sure, here's how things work right now:

- There is "public" documentation mode, where anyone can do anything (not typically used)
- There is "public read" and "auth edit" as you see in your config file. This is typically fine for most cases
- There is also "no public" where anyone has to authenticate to view/edit.

Whenever someone auths, they are automatically an admin.
Since Raneto is designed more for an internal small company documentation platform, employees can be admins most times.

What you're looking to do is completely understandable
This requires some rethinking of how Raneto has evolved, with each of the above features added over the years.
Essentially, your design is something called "permissions scoping" or "roles".
We'd have multiple "roles" (admin, employee, public, etc) that each are handed out "permissions" (scope like "read", "write", "settings").
These scopes can even go into detail on viewing/editing certain sections of the sites and not others

This is probably going to involve a big chunk of work because it'll fundamentally shift some of the core code.

I completely agree with you this is valuable.
I'll mark it down as a "Request for PR"

**Comment by ryanlelek** [comment]
Thank you for submitting.
Adding this to the Roadmap (see link above this comment)
Let's continue discussion there. Closing this issue

Link: #112 and #168
